apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-adapter-nodejs-config
  labels:
    app: mqtt-adapter-nodejs
data:
  ADAPTER_MQTT_PORT: "1881"

  MAINFLUX_HOST: "mqtt://host.docker.internal:1883"

  USER_NAME_DEFAULT: "2f732718-802b-4d46-97ba-2a47dce22fb5"
  PASSWORD_DEFAULT: "01eb9309-a9f0-1040-9681-fd79e5ecd395"
  CHANNEL_DEFAULT: "/channels/8ebc51a7-86c8-48b3-bee8-e89320323f19/messages"

  REDIS_MASTER: "mymaster"
  REDIS_SENTINEL_1: "10.16.150.141"
  REDIS_SENTINEL_PORT_1: "26379"
  REDIS_SENTINEL_2: "10.16.150.142"
  REDIS_SENTINEL_PORT_2: "26379"
  REDIS_SENTINEL_3: "10.16.150.134"
  REDIS_SENTINEL_PORT_3: "26379"
